### ISSUE TITLE
Cannot set global configurations for Jest-Image-Snapshot

### ISSUE THREAD

**Issue by fgaleano** [Hapag-Lloyd/jest-puppeteer-react#60]
With the way `jest-image-snapshot- is included in this library, it is impossible to define global configurations for that module. For instance, we're facing issues with very small differences in visual tests and we can solve it by increase the threshold. But because we can't do it at the global level, we have to do it on a test-by-test basis which is troublesome.

I'll look at the code later and see if I can contribute the change, but I hope it can be added to as fix for any future releases.

Thanks!

**Comment by doochik** [comment]
You can do it

jest.config.js
```
{
....
    preset: 'jest-puppeteer-react',
    setupFilesAfterEnv: [
        './setup.js',
    ],
...
}
```

setup.js
```
require('expect-puppeteer');

const { configureToMatchImageSnapshot } = require('jest-image-snapshot');
const toMatchImageSnapshot = configureToMatchImageSnapshot({
    failureThreshold: '0.04',
    failureThresholdType: 'percent',
});
expect.extend({ toMatchImageSnapshot });

```
