### ISSUE TITLE
global jestPuppeteer

### ISSUE THREAD

**Issue by albinotonnina** [Hapag-Lloyd/jest-puppeteer-react#7]
Hi!
Thanks for this. Experimenting with this library here: https://github.com/albinotonnina/react-truncate-string

I noticed that the global obj jestPuppeteer is undefined with jest-puppeteer-react: https://github.com/smooth-code/jest-puppeteer#put-in-debug-mode

Is it a bug?

Thanks!

**Comment by ansgarm** [comment]
Hi!

Yeah, we're on an old version of the lib currently.
I'll have a look into your PR #8 later :)

**Comment by albinotonnina** [comment]
Thanks! Sorry, I forgot to mention here what was the cause of the missing global :)

**Comment by ansgarm** [comment]
I just published a new version. See 2.0.0 :)
